version: '2'

services:   

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers_configs/portainer/data:/data
    restart: always
    ports:
      - 9000:9000
      - 8000:8000

  mariadb:
    build: ./mariadb
    volumes:
      - volume_mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: scrapy
      MYSQL_PASSWORD: scrapy
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # #- MYSQL_RANDOM_ROOT_PASSWORD=yes

  scrapy:
    build: ./scrapy
    volumes:
      - /home/pi/containers_configs/scrapy:/app/projects
      - volume_scrapy_crontabs:/usr/lib/node_modules/crontab-ui/crontabs
    ports:
      - 8881:8000
    restart: unless-stopped
    environment:
      #- CRON_PATH=/var/spool/cron
      - HOST=0.0.0.0 
      #- PORT=9000

      
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - volume_grafana_config:/etc/grafana
      - volume_grafana_data:/var/lib/grafana
      - volume_grafana_home:/usr/share/grafana
      #- volume_grafana_plugins:/var/lib/grafana/plugins
      #- volume_grafana_provisioning:/etc/grafana/provisioning
    depends_on:
      - mariadb

  zigbee2mqttAssistant:
    image: carldebilly/zigbee2mqttassistant
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mosquitto
      #- Z2MA_SETTINGS__MQTTUSERNAME={MQTTUSERNAME}
      #- Z2MA_SETTINGS__MQTTPASSWORD={MQTTPASSWORD}
      # Set to your TimeZone when using on Linux https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Won't work if you're using the Windows version of the container
      - TZ=Europe/Warsaw
    ports:
      - 8880:80
    restart: unless-stopped
    depends_on: 
      - mosquitto

  zigbee2mqtt:
#    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/pi/containers_configs/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    depends_on: 
      - mosquitto
    environment:
      - TZ=Europe/Warsaw

  duplicati:
     build: ./duplicati
     ports:
       - 8200:8200
     restart: unless-stopped
     volumes:
       - /media/1TB/share_net:/media/1TB/share_net
       - /media/backup/duplicati:/media/backup/duplicati
       - /home/pi/containers_configs/duplicati/:/data

  syncthing:
    build: ./syncthing
    ports:
      - 8384:8384
    restart: unless-stopped
    volumes:
      - /home/pi/containers_configs/syncthing/config:/syncthing/config
      - /home/pi/containers_configs/syncthing/data:/syncthing/data
      - /media/1TB/share_net:/media/1TB/share_net

  syncthing2:
    build: ./syncthing2
    ports:
      - 8385:8385
    restart: unless-stopped
    volumes:
      - /home/pi/containers_configs/syncthing2/config:/syncthing/config
      - /home/pi/containers_configs/syncthing2/data:/syncthing/data
      - /media/backup:/media/backup
    environment:
      - GUI_ADDRESS=[::]:8385

  mpd:
    build: ./mpd
    ports:
      - 6600:6600
    depends_on: 
     - pulseaudio
    volumes:
      - volume_mpd:/config
      - /media/1TB/media/muzyka:/media/muzyka
    restart: unless-stopped

  mpd_client_ympd:
    build: ./mpd_client_ympd
    ports:
      - 81:81
    depends_on: 
      - mpd
    # volumes:
    #   - /media/1TB/media/muzyka:/media/muzyka 
    restart: unless-stopped

  motioneye:
    build: ./motioneye
    ports:
      - 8765:8765
      - 8081:8081
    hostname: motioneye
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/containers_configs/motioneye:/etc/motioneye
      - /home/pi/containers_configs/motioneye/records:/var/lib/motioneye
      - /dev:/dev
    #devices:
    #  - "/dev/video0"
    restart: unless-stopped


  node-red:
    build: ./node-red
    ports:
      - 1880:1880
    depends_on:
      - homeassistant
    volumes:
      - volume_node-red:/data
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw

  homeassistant:
    build: ./homeassistant
    ports:
      - 8123:8123
    depends_on: 
      - mosquitto
    volumes:
      - /home/pi/containers_configs/homeassistant:/config
      # - /var/run/dbus:/var/run/dbus
      # - /dev/bus/usb:/dev/bus/usb
      # - /opt/bluetooth:/var/lib/bluetooth
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro

    restart: unless-stopped
    # cap_add:
    #   - ALL
    #devices:
    #  - /dev/bus/usb/001/009
    network_mode: host

  mosquitto:
    build: ./mosquitto
    ports:
      - 1883:1883/tcp
    restart: unless-stopped 

  samba:
    build: ./samba
    ports:
      - "445:445"
    volumes: 
      - /media/transmission:/media/transmission
      - /media/1TB:/media/1TB
      - /media/500GB:/media/500GB
      - /home/pi/containers_configs/homeassistant:/share/homeassistant
      - /home/pi/containers_configs/scrapy:/share/scrapy
      - /media/backup:/media/backup
    restart: unless-stopped

  transmission:
    build: ./transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    volumes: 
      - /media/transmission:/media/transmission
      - /home/pi/containers_configs/transmission-daemon:/etc/transmission-daemon

  # mopidy:
  #   build: ./mopidy
  #   ports:
  #     - 6680:6680/tcp
  #     - 6600:6600
  #   depends_on: 
  #     - pulseaudio
  #   volumes:
  #     - /media/1TB/media/muzyka:/var/lib/mopidy/file
  #     - /home/pi/containers_configs/mopidy/m3u:/var/lib/mopidy/.local/share/mopidy/m3u
  #     - /media/1TB/media/muzyka:/var/lib/mopidy/.local/share/mopidy/local
  #     - /home/pi/containers_configs/mopidy/local-images:/var/lib/mopidy/.local/share/mopidy/local-images

  pulseaudio:
    build: ./pulseaudio
    ports:
      - 4713:4713/tcp
      - 8001:8000
    restart: unless-stopped
    volumes: 
      - /var/run/dbus:/var/run/dbus
      # - /dev/shm:/dev/shm
      # - /dev:/dev
      - /home/pi:/audio
      #- /proc/asound/card0:/proc/asound/card0
    devices:
      - /dev/snd
      # - /dev/snd/controlC0
      # - /dev/snd/pcmC0D0p
      # - /dev/snd/pcmC0D1p
      # - /dev/snd/pcmC0D2p
      # - /dev/snd/timer

volumes:
    volume_node-red: {}
    volume_mpd: {}
    volume_grafana_config: {}
    volume_grafana_data: {}
    volume_grafana_home: {}
    volume_mariadb_data: {}
    volume_scrapy_crontabs: {}


