version: '2'

services:
  # samba:
  #   build: ./samba
  #   ports:
  #     - "445:445"
  #   volumes: 
  #     - /media/transmission:/media/transmission
  #     - /media/1TB:/media/1TB
  #     - /media/500GB:/media/500GB
  #     - /home/pi/homeassistant:/share/homeassistant
  #     - /media/backup:/media/backup
  # transmission:
  #   build: ./transmission
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   restart: always
  #   volumes: 
  #     - /media/transmission:/media/transmission
  #     - /home/pi/containers_configs/transmission-daemon:/etc/transmission-daemon
  mopidy:
    build: ./mopidy
    ports:
      - 6680:6680/tcp
    #links:
    #  - pulseaudio
    volumes:
      - /media/1TB/media/muzyka:/var/lib/mopidy/file
      - /home/pi/containers_configs/mopidy/m3u:/var/lib/mopidy/.local/share/mopidy/m3u
      - /media/1TB/media/muzyka:/var/lib/mopidy/.local/share/mopidy/local
      - /home/pi/containers_configs/mopidy/local-images:/var/lib/mopidy/.local/share/mopidy/local-images

    devices:
      - "/dev/snd"
  pulseaudio:
    build: ./pulseaudio
    ports:
      - 4713:4713/tcp
    restart: always
    volumes: 
      - /var/run/dbus:/var/run/dbus
