version: '2'

services:

  motioneye:
    build: ./motioneye
    ports:
      - 8765:8765
      - 8081:8081
    hostname: motioneye
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/containers_configs/motioneye:/etc/motioneye
      - /home/pi/containers_configs/motioneye/records:/var/lib/motioneye
      - /dev:/dev
    #devices:
    #  - "/dev/video0"
    restart: always


  node-red:
    build: ./node-red
    ports:
      - 1880:1880
    depends_on:
      - homeassistant
    volumes:
      - volume_node-red:/data


  homeassistant:
    build: ./homeassistant
    ports:
      - 8123:8123
    depends_on: 
      - mosquitto
    volumes:
      - /home/pi/containers_configs/homeassistant:/config

  mosquitto:
    build: ./mosquitto
    ports:
      - 1883:1883/tcp
    restart: unless-stopped 

  samba:
    build: ./samba
    ports:
      - "445:445"
    volumes: 
      - /media/transmission:/media/transmission
      - /media/1TB:/media/1TB
      - /media/500GB:/media/500GB
      - /home/pi/containers_configs/homeassistant:/share/homeassistant
      - /media/backup:/media/backup

  transmission:
    build: ./transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
    volumes: 
      - /media/transmission:/media/transmission
      - /home/pi/containers_configs/transmission-daemon:/etc/transmission-daemon

  mopidy:
    build: ./mopidy
    ports:
      - 6680:6680/tcp
      - 6600:6600
    depends_on: 
      - pulseaudio
    volumes:
      - /media/1TB/media/muzyka:/var/lib/mopidy/file
      - /home/pi/containers_configs/mopidy/m3u:/var/lib/mopidy/.local/share/mopidy/m3u
      - /media/1TB/media/muzyka:/var/lib/mopidy/.local/share/mopidy/local
      - /home/pi/containers_configs/mopidy/local-images:/var/lib/mopidy/.local/share/mopidy/local-images
    devices:
      - "/dev/snd"

  pulseaudio:
    build: ./pulseaudio
    ports:
      - 4713:4713/tcp
    restart: always
    volumes: 
      - /var/run/dbus:/var/run/dbus

volumes:
    volume_node-red: {}
