version: '2'

services:

  syncthing:
    build: ./syncthing
    #image: funkyfuture/rpi-syncthing
    ports:
      - 8384:8384
    restart: unless-stopped
    volumes:
      - /home/pi/containers_configs/syncthing/config:/syncthing/config
      - /home/pi/containers_configs/syncthing/data:/syncthing/data
      - /media/1TB/share_net:/media/1TB/share_net
    # environment:
    #   - UID=0
    #   - GID=0

  syncthing2:
    build: ./syncthing2
    #image: funkyfuture/rpi-syncthing
    ports:
      - 8385:8385
    restart: unless-stopped
    volumes:
      - /home/pi/containers_configs/syncthing2/config:/syncthing/config
      - /home/pi/containers_configs/syncthing2/data:/syncthing/data
      - /media/backup:/media/backup
    environment:
      - GUI_ADDRESS=[::]:8385
      # - UID=0
      # - GID=0

  mpd:
    build: ./mpd
    ports:
      - 6600:6600
    depends_on: 
     - pulseaudio
    volumes:
      - volume_mpd:/config
      - /media/1TB/media/muzyka:/media/muzyka

  mpd_client_ympd:
    build: ./mpd_client_ympd
    ports:
      - 81:81
    depends_on: 
      - mpd
    # volumes:
    #   - /media/1TB/media/muzyka:/media/muzyka 


  motioneye:
    build: ./motioneye
    ports:
      - 8765:8765
      - 8081:8081
    hostname: motioneye
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/containers_configs/motioneye:/etc/motioneye
      - /home/pi/containers_configs/motioneye/records:/var/lib/motioneye
      - /dev:/dev
    #devices:
    #  - "/dev/video0"
    restart: always


  node-red:
    build: ./node-red
    ports:
      - 1880:1880
    depends_on:
      - homeassistant
    volumes:
      - volume_node-red:/data


  homeassistant:
    build: ./homeassistant
    ports:
      - 8123:8123
    depends_on: 
      - mosquitto
    volumes:
      - /home/pi/containers_configs/homeassistant:/config

  mosquitto:
    build: ./mosquitto
    ports:
      - 1883:1883/tcp
    restart: unless-stopped 

  samba:
    build: ./samba
    ports:
      - "445:445"
    volumes: 
      - /media/transmission:/media/transmission
      - /media/1TB:/media/1TB
      - /media/500GB:/media/500GB
      - /home/pi/containers_configs/homeassistant:/share/homeassistant
      - /media/backup:/media/backup

  transmission:
    build: ./transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
    volumes: 
      - /media/transmission:/media/transmission
      - /home/pi/containers_configs/transmission-daemon:/etc/transmission-daemon

  # mopidy:
  #   build: ./mopidy
  #   ports:
  #     - 6680:6680/tcp
  #     - 6600:6600
  #   depends_on: 
  #     - pulseaudio
  #   volumes:
  #     - /media/1TB/media/muzyka:/var/lib/mopidy/file
  #     - /home/pi/containers_configs/mopidy/m3u:/var/lib/mopidy/.local/share/mopidy/m3u
  #     - /media/1TB/media/muzyka:/var/lib/mopidy/.local/share/mopidy/local
  #     - /home/pi/containers_configs/mopidy/local-images:/var/lib/mopidy/.local/share/mopidy/local-images

  pulseaudio:
    build: ./pulseaudio
    ports:
      - 4713:4713/tcp
    restart: always
    volumes: 
      - /var/run/dbus:/var/run/dbus
      # - /dev/shm:/dev/shm
      # - /dev:/dev
      - /home/pi:/audio
      #- /proc/asound/card0:/proc/asound/card0
    devices:
      - /dev/snd
      # - /dev/snd/controlC0
      # - /dev/snd/pcmC0D0p
      # - /dev/snd/pcmC0D1p
      # - /dev/snd/pcmC0D2p
      # - /dev/snd/timer

volumes:
    volume_node-red: {}
    volume_mpd: {}
